import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import StoreProvider from '@/libs/redux/store-provider'
import Menu from '@/components/sidebar/menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoreProvider>
			<html
				lang='en'
				className='dark'>
				<body className={inter.className}>
					<ThemeProvider
						enableSystem={true}
						attribute='class'>
						<div className='flex'>
							<Menu />
							{children}
						</div>
					</ThemeProvider>
				</body>
			</html>
		</StoreProvider>
	)
}
